config/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseServerError
from django.template import loader
from django.urls import include, path
from django.views.generic import TemplateView

logger = logging.getLogger(__name__)

admin.autodiscover()

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("navsearch/", include("poradnia.navsearch.urls", namespace="navsearch")),
    # User management
    path("uzytkownik/klucze", include("poradnia.keys.urls", namespace="keys")),
    path("uzytkownik/", include("poradnia.users.urls", namespace="users")),
    path("konta/", include("allauth.urls")),
    # Poradnia
    path("sprawy/", include("poradnia.cases.urls", namespace="cases")),
    path("listy/", include("poradnia.letters.urls", namespace="letters")),
    path("wydarzenia/", include("poradnia.events.urls", namespace="events")),
    path("porady/", include("poradnia.advicer.urls", namespace="advicer")),
    path("uwagi/", include("poradnia.tasty_feedback.urls", namespace="tasty_feedback")),
    path("sprawy_sadowe/", include("poradnia.judgements.urls", namespace="judgements")),
    path("teryt/", include("poradnia.teryt.urls", namespace="teryt")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt")),
    path(
        "strony/regulamin-poradnictwa/",
        TemplateView.as_view(template_name="pages/terms.html"),
        name="terms",
    ),
    path(
        "strony/polityka-prywatnosci/",
        TemplateView.as_view(template_name="pages/privacy.html"),
        name="privacy",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    except ImportError:
        logger.warning("Could not import debug_toolbar.")


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """

    t = loader.get_template("500.html")
    return HttpResponseServerError(t.render({"request": request}))

poradnia/judgements/urls.py
from django.urls import path

from poradnia.judgements import views

urlpatterns = [
    path("~create-<int:case_pk>", views.CourtCaseCreateView.as_view(), name="create"),
    path(
        "courtcase-<int:pk>/~update", views.CourtCaseUpdateView.as_view(), name="update"
    ),
    path(
        "courtcase-<int:pk>/~delete", views.CourtCaseDeleteView.as_view(), name="delete"
    ),
]

app_name = "poradnia.judgements"

poradnia/keys/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.KeyListView.as_view(), name="list"),
    path("<int:pk>/", views.KeyDetailView.as_view(), name="details"),
    path("<int:pk>/usun/", views.KeyDeleteView.as_view(), name="delete"),
    path("stworz/", views.KeyCreateView.as_view(), name="create"),
]

app_name = "poradnia.keys"

poradnia/letters/urls.py
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt

from . import views

urlpatterns = [
    path("webhook", csrf_exempt(views.ReceiveEmailView.as_view()), name="webhook"),
    path("rejestr", views.LetterListView.as_view(), name="list"),
    path(
        "table/",
        views.cbv.LetterTableView.as_view(),
        name="table",
    ),
    path(
        "letters_table_ajax_data/",
        views.cbv.LetterAjaxDatatableView.as_view(),
        name="letters_table_ajax_data",
    ),
    path("sprawa-<int:case_pk>/", views.add, name="add"),
    path(
        "sprawa-<int:case_pk>/list-<int:letter_pk>/zalaczniki",
        views.StreamAttachmentView.as_view(),
        name="attachments_zip",
    ),
    path(
        "sprawa-<int:case_pk>/list-<int:letter_pk>/zalacznik/<int:pk>",
        views.DownloadAttachmentView.as_view(),
        name="attachment_download",
    ),
    path("<int:pk>/wyslij/", views.send, name="send"),
    path("<int:pk>/edytuj/", views.LetterUpdateView.as_view(), name="edit"),
    path("<int:pk>/", views.send, name="detail"),
    path("", views.NewCaseCreateView.as_view(), name="home"),
    path("", views.NewCaseCreateView.as_view(), name="add"),
    path("tinymce/", include("tinymce.urls")),
]

app_name = "poradnia.letters"

poradnia/keys/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from poradnia.users.models import User

from .utils import make_random_password


class KeyQuerySet(QuerySet):
    def for_user(self, user):
        return self.filter(user=user)


class Key(models.Model):
    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE)
    password = models.CharField(
        max_length=75, default=make_random_password, verbose_name=_("Key")
    )
    description = models.CharField(max_length=75, verbose_name=_("Description"))
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_("Created on"))
    used_on = models.DateTimeField(null=True, verbose_name=_("Used on"))
    download_on = models.DateTimeField(null=True, verbose_name=_("Download on"))
    objects = KeyQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse("keys:details", kwargs={"pk": self.pk})

    def __str__(self):
        return "%s" % (self.created_on)

    class Meta:
        unique_together = (("user", "password"),)
        verbose_name = _("Access key")
        verbose_name_plural = _("Access keys")

poradnia/keys/forms.py
from atom.ext.crispy_forms.forms import SingleButtonMixin
from braces.forms import UserKwargModelFormMixin
from django.forms import ModelForm

from .models import Key


class KeyForm(UserKwargModelFormMixin, SingleButtonMixin, ModelForm):
    class Meta:
        model = Key
        fields = ["description"]

    def save(self, commit=True, *args, **kwargs):
        obj = super().save(commit=False, *args, **kwargs)
        obj.user = self.user
        if commit:
            obj.save()
        return obj

poradnia/keys/views.py
from atom.views import DeleteMessageMixin
from braces.views import UserFormKwargsMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, ListView

from poradnia.users.utils import PermissionMixin, SuperuserPermissionMixin

from .forms import KeyForm
from .models import Key


class KeyCreateView(
    SuperuserPermissionMixin, PermissionMixin, UserFormKwargsMixin, CreateView
):
    form_class = KeyForm
    model = Key


class KeyDetailView(SuperuserPermissionMixin, PermissionMixin, DetailView):
    model = Key

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)
        obj.download_on = now()
        obj.save()
        messages.add_message(
            self.request, messages.SUCCESS, "{object} downloaded!".format(object=obj)
        )
        return obj


class KeyDeleteView(
    SuperuserPermissionMixin, PermissionMixin, DeleteMessageMixin, DeleteView
):
    model = Key
    success_url = reverse_lazy("list")

    def get_success_message(self):
        return _("{object} deleted!").format(object=self.object)


class KeyListView(SuperuserPermissionMixin, PermissionMixin, ListView):
    model = Key

poradnia/keys/templates/keys/base.html
{% extends 'base.html' %}
{% load i18n %}
{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="{% url 'users:list' %}">{% trans 'Users' %}</a></li>
        <li><a href="{% url 'users:detail' username=user.username %}">{{ user }}</a></li>
        {% if user.is_superuser %}
            <li><a href="{% url 'keys:list' %}">{% trans 'Keys' %}</a></li>
        {% endif %}
        {% block breadcrumbs_rows %}{% endblock %}
    </ol>
{% endblock %}

poradnia/keys/templates/keys/key_confirm_delete.html
{% extends 'keys/base.html' %}
{% load i18n %}
{% block breadcrumbs_rows %}
    <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
    <li class="active">{% trans 'Confirm delete' %}</li>
{% endblock %}
{% block content %}
    <form method="post">
        <div class="form-actions">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger"><i class="fas fa-trash-can"></i> {% blocktrans %}Delete
                {{ object }}{% endblocktrans %}</button>
            <button class="btn" href="{{ object.get_absolute_url }}">{% trans 'Cancel' %}</button>
        </div>
    </form>
{% endblock %}

poradnia/keys/templates/keys/key_detail.html
{% extends 'keys/base.html' %}
{% load crispy_forms_tags i18n %}

{% block breadcrumbs_rows %}
    <li class="active">{{ object }}</li>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1>{% block header %}{% trans 'Key' %} - {{ object }}{% endblock %}</h1>
            <pre>{{ object.password }}</pre>
        </div>
    </div>
{% endblock %}

poradnia/keys/templates/keys/key_form.html
{% extends 'keys/base.html' %}
{% load crispy_forms_tags i18n %}

{% block breadcrumbs_rows %}
    <li class="active">{% trans 'New key' %}</li>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1>{% block header %}{% trans 'New key' %}{% endblock %}</h1>
            <form method="post">
                {% csrf_token %}
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

poradnia/keys/templates/keys/key_list.html
{% extends 'keys/base.html' %}
{% load i18n humanize %}

{% block breadcrumbs_rows %}
    <li class="active">{% trans 'Keys index' %}</li>
{% endblock %}

{% block content %}
    <div class="text-right">
        <p><a href="https://github.com/watchdogpolska/poradnia/blob/master/docs/modules/keys.rst" class="btn btn-primary"><i
                class="fas fa-question"></i> {% trans 'Help' %}</a>
            <a href="{% url 'keys:create' %}" class="btn btn-primary"><i
                    class="fas fa-gear"></i> {% trans 'Generate new key' %}</a></p>
    </div>
    <table class="table table-stripped table-keys">
        <tr>
            <th>{% trans 'Description' %}</th>
            <th>{% trans 'Created on' %}</th>
            <th>{% trans 'Downloaded on' %}</th>
            <th>{% trans 'Used on' %}</th>
            <th>{% trans 'Actions' %}</th>
        </tr>
        {% for object in object_list %}
            <tr>
                <td>{{ object.description }}</td>
                <td>{{ object.created_on|naturaltime }}</td>
                <td>{{ object.download_on|naturaltime }}</td>
                <td>{{ object.used_on|naturaltime }}</td>
                <td>
                    <a href="{% url 'keys:details' pk=object.pk %}" class="btn btn-default"><i
                            class="fas fa-download"></i>{% trans 'Download' %}</a>
                    <a href="{% url 'keys:delete' pk=object.pk %}" class="btn btn-default"><i
                            class="fas fa-trash-can"></i>{% trans 'Delete' %}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}