config/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseServerError
from django.template import loader
from django.urls import include, path
from django.views.generic import TemplateView

logger = logging.getLogger(__name__)

admin.autodiscover()

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("navsearch/", include("poradnia.navsearch.urls", namespace="navsearch")),
    # User management
    path("uzytkownik/klucze", include("poradnia.keys.urls", namespace="keys")),
    path("uzytkownik/", include("poradnia.users.urls", namespace="users")),
    path("konta/", include("allauth.urls")),
    # Poradnia
    path("sprawy/", include("poradnia.cases.urls", namespace="cases")),
    path("listy/", include("poradnia.letters.urls", namespace="letters")),
    path("wydarzenia/", include("poradnia.events.urls", namespace="events")),
    path("porady/", include("poradnia.advicer.urls", namespace="advicer")),
    path("uwagi/", include("poradnia.tasty_feedback.urls", namespace="tasty_feedback")),
    path("sprawy_sadowe/", include("poradnia.judgements.urls", namespace="judgements")),
    path("teryt/", include("poradnia.teryt.urls", namespace="teryt")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt")),
    path(
        "strony/regulamin-poradnictwa/",
        TemplateView.as_view(template_name="pages/terms.html"),
        name="terms",
    ),
    path(
        "strony/polityka-prywatnosci/",
        TemplateView.as_view(template_name="pages/privacy.html"),
        name="privacy",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    except ImportError:
        logger.warning("Could not import debug_toolbar.")


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """

    t = loader.get_template("500.html")
    return HttpResponseServerError(t.render({"request": request}))

poradnia/advicer/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.AdviceList.as_view(), name="list"),
    path(
        "table/",
        views.AdviceTableView.as_view(),
        name="table",
    ),
    path(
        "advice_table_ajax_data/",
        views.AdviceAjaxDatatableView.as_view(),
        name="advice_table_ajax_data",
    ),
    path("nowa/", views.AdviceCreate.as_view(), name="create"),
    path("<int:pk>", views.AdviceDetail.as_view(), name="detail"),
    path("<int:pk>/edytuj/", views.AdviceUpdate.as_view(), name="update"),
    path("<int:pk>/usun/", views.AdviceDelete.as_view(), name="delete"),
    path(
        "issue-autocomplete/",
        views.IssueAutocomplete.as_view(),
        name="issue-autocomplete",
    ),
    path(
        "area-autocomplete/", views.AreaAutocomplete.as_view(), name="area-autocomplete"
    ),
]

app_name = "poradnia.advicer"

poradnia/judgements/urls.py
from django.urls import path

from poradnia.judgements import views

urlpatterns = [
    path("~create-<int:case_pk>", views.CourtCaseCreateView.as_view(), name="create"),
    path(
        "courtcase-<int:pk>/~update", views.CourtCaseUpdateView.as_view(), name="update"
    ),
    path(
        "courtcase-<int:pk>/~delete", views.CourtCaseDeleteView.as_view(), name="delete"
    ),
]

app_name = "poradnia.judgements"

poradnia/letters/urls.py
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt

from . import views

urlpatterns = [
    path("webhook", csrf_exempt(views.ReceiveEmailView.as_view()), name="webhook"),
    path("rejestr", views.LetterListView.as_view(), name="list"),
    path(
        "table/",
        views.cbv.LetterTableView.as_view(),
        name="table",
    ),
    path(
        "letters_table_ajax_data/",
        views.cbv.LetterAjaxDatatableView.as_view(),
        name="letters_table_ajax_data",
    ),
    path("sprawa-<int:case_pk>/", views.add, name="add"),
    path(
        "sprawa-<int:case_pk>/list-<int:letter_pk>/zalaczniki",
        views.StreamAttachmentView.as_view(),
        name="attachments_zip",
    ),
    path(
        "sprawa-<int:case_pk>/list-<int:letter_pk>/zalacznik/<int:pk>",
        views.DownloadAttachmentView.as_view(),
        name="attachment_download",
    ),
    path("<int:pk>/wyslij/", views.send, name="send"),
    path("<int:pk>/edytuj/", views.LetterUpdateView.as_view(), name="edit"),
    path("<int:pk>/", views.send, name="detail"),
    path("", views.NewCaseCreateView.as_view(), name="home"),
    path("", views.NewCaseCreateView.as_view(), name="add"),
    path("tinymce/", include("tinymce.urls")),
]

app_name = "poradnia.letters"

poradnia/advicer/models.py
from atom.models import AttachmentBase
from django.conf import settings
from django.db import models
from django.db.models import Case as djCase
from django.db.models import CharField, F, Q, Value, When
from django.db.models.query import QuerySet
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from teryt_tree.dal_ext.filters import AreaMultipleFilter

from poradnia.cases.models import Case
from poradnia.teryt.models import JST
from poradnia.utils.mixins import FormattedDatetimeMixin, UserPrettyNameMixin


class AbstractCategory(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"))

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Issue(AbstractCategory):
    class Meta:
        verbose_name = _("The thematic scope of the request")
        verbose_name_plural = _("Thematic scopes of requests")


class Area(AbstractCategory):
    class Meta:
        verbose_name = _("Problem regarding the right to information")
        verbose_name_plural = _("Problems regarding the right to information")


class PersonKind(AbstractCategory):
    class Meta:
        verbose_name = _("Type of person who reporting the advice")
        verbose_name_plural = _("Types of people who report to for advice")


class InstitutionKind(AbstractCategory):
    class Meta:
        verbose_name = _("Institution kind")
        verbose_name_plural = _("Institution kinds")


class AdviceQuerySet(FormattedDatetimeMixin, UserPrettyNameMixin, QuerySet):
    def for_user(self, user):
        if user.has_perm("advicer.can_view_all_advices"):
            return self
        return self.filter(Q(advicer=user.pk) | Q(created_by=user.pk))

    def visible(self):
        return self.filter(visible=True)

    def area_filter(self, jst):
        return self.filter(
            jst__tree_id=jst.tree_id, jst__lft__range=(jst.lft, jst.rght)
        )

    def area_in(self, jsts):
        if not jsts:
            # Show all results if filter is empty.
            return self
        else:
            return AreaMultipleFilter.filter_area_in(self, jsts, "jst")

    def with_helped_str(self):
        return self.annotate(
            helped_str=djCase(
                When(helped=True, then=Value(_("Yes"))),
                When(helped=False, then=Value(_("No"))),
                default=Value("-"),
                output_field=CharField(),
            ),
        )

    def with_visible_str(self):
        return self.annotate(
            visible_str=djCase(
                When(visible=True, then=Value(_("Yes"))),
                When(visible=False, then=Value(_("No"))),
                default=Value("-"),
                output_field=CharField(),
            ),
        )

    def with_jst_name_str(self):
        return self.annotate(
            jst_name=djCase(
                When(jst__name__isnull=False, then=F("jst__name")),
                default=Value("-"),
                output_field=CharField(),
            ),
        )


class Advice(models.Model):
    case = models.OneToOneField(
        to=Case, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_("Case")
    )
    subject = models.CharField(
        max_length=100, verbose_name=_("Subject"), null=True, blank=True
    )
    issues = models.ManyToManyField(
        to=Issue, verbose_name=Issue._meta.verbose_name_plural, blank=True
    )
    area = models.ManyToManyField(
        to=Area, verbose_name=Area._meta.verbose_name_plural, blank=True
    )
    person_kind = models.ForeignKey(
        PersonKind,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name=PersonKind._meta.verbose_name,
    )
    institution_kind = models.ForeignKey(
        to=InstitutionKind,
        verbose_name=InstitutionKind._meta.verbose_name,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    advicer = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        verbose_name=_("Advicer"),
        help_text=_("Person who give a advice"),
        limit_choices_to={"is_staff": True},
        on_delete=models.CASCADE,
    )
    grant_on = models.DateTimeField(default=now, verbose_name=_("Grant on"))
    created_by = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        verbose_name=_("Created by"),
        related_name="advice_created_by",
        on_delete=models.CASCADE,
    )
    created_on = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation date")
    )
    helped = models.BooleanField(verbose_name=_("We helped?"), null=True, blank=True)
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        verbose_name=_("Modified by"),
        related_name="advice_modified_by",
        on_delete=models.CASCADE,
    )
    modified_on = models.DateTimeField(
        auto_now=True, null=True, blank=True, verbose_name=_("Modification date")
    )
    visible = models.BooleanField(default=True, verbose_name=_("Visible"))
    comment = models.TextField(verbose_name=_("Comment"), null=True, blank=True)
    jst = models.ForeignKey(
        to=JST,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name=_("Unit of administrative division"),
        db_index=True,
    )
    objects = AdviceQuerySet.as_manager()

    def __str__(self):
        return self.subject or _("Advice #%d") % (self.pk)

    def get_absolute_url(self):
        return reverse("advicer:detail", kwargs={"pk": self.pk})

    def render_advice_link(self):
        url = self.get_absolute_url()
        label = self.subject
        return f'<a href="{url}">{label}</a>'

    def render_helped(self):
        if self.helped is None:
            return '<span class="fas fa-question"></span>'
        elif self.helped:
            return '<span class="fas fa-check" style="color: green;"></span>'
        return '<span class="fas fa-xmark" style="color: red;"></span>'

    def render_visible(self):
        if self.visible:
            return '<span class="fas fa-check" style="color: green;"></span>'
        return '<span class="fas fa-xmark" style="color: red;"></span>'

    class Meta:
        ordering = ["-created_on"]
        permissions = (("can_view_all_advices", _("Can view all advices")),)
        verbose_name = _("Advice")
        verbose_name_plural = _("Advices")


class Attachment(AttachmentBase):
    advice = models.ForeignKey(to=Advice, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Attachment")
        verbose_name_plural = _("Attachments")

poradnia/advicer/views/advice.py
# from django.shortcuts import render
from django.views.generic import UpdateView, CreateView, DeleteView, DetailView
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from braces.views import (OrderableListMixin, SelectRelatedMixin, LoginRequiredMixin,
    FormValidMessageMixin, UserFormKwargsMixin)
from django_filters.views import FilterView
from users.mixins import PermissionMixin
from utilities.views import DeleteMessageMixin
from ..filters import AdviceFilter
from ..models import Advice
from ..forms import AdviceForm
from .mixins import FormInitialMixin


class AdviceList(PermissionMixin, SelectRelatedMixin,
        OrderableListMixin, FilterView):
    model = Advice
    filterset_class = AdviceFilter
    orderable_columns = ("id", "advicer", "person_kind", "institution_kind")
    orderable_columns_default = "created_on"
    select_related = ["person_kind", "created_by", "advicer", "institution_kind"]
    paginate_by = 25

    def get_queryset(self, *args, **kwargs):
        qs = super(AdviceList, self).get_queryset(*args, **kwargs)
        return qs.visible()


class AdviceUpdate(PermissionMixin, FormValidMessageMixin, UserFormKwargsMixin, UpdateView):
    model = Advice
    form_class = AdviceForm

    def get_form_valid_message(self):
        return _("{0} updated!").format(self.object)


class AdviceCreate(FormInitialMixin, FormValidMessageMixin, UserFormKwargsMixin, LoginRequiredMixin,
        CreateView):
    model = Advice
    form_class = AdviceForm

    def get_form_valid_message(self):
        return _("{0} created!").format(self.object)


class AdviceDelete(PermissionMixin, DeleteMessageMixin, DeleteView):
    model = Advice
    success_url = reverse_lazy('advicer:list')
    success_message = _("{__unicode__} deleted!")
    hide_field = 'visible'


class AdviceDetail(PermissionMixin, DetailView):
    model = Advice

poradnia/registers/views/advice.py
# from django.shortcuts import render
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, DetailView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from braces.views import (OrderableListMixin, SelectRelatedMixin, LoginRequiredMixin,
    FormValidMessageMixin, UserFormKwargsMixin)
from ..filters import AdviceFilter
from ..models import Advice
from ..forms import AdviceForm
from .mixins import PermissionMixin
from django_filters.views import FilterView


class AdviceList(PermissionMixin, SelectRelatedMixin,
        OrderableListMixin, FilterView):
    model = Advice
    filterset_class = AdviceFilter
    orderable_columns = ("id", "advicer", "person_kind", "institution_kind")
    orderable_columns_default = "created_on"
    select_related = ["person_kind", "created_by", "advicer", "institution_kind"]
    paginate_by = 25

    def get_queryset(self, *args, **kwargs):
        qs = super(AdviceList, self).get_queryset(*args, **kwargs)
        return qs.visible()


class AdviceUpdate(PermissionMixin, FormValidMessageMixin, UserFormKwargsMixin, UpdateView):
    model = Advice
    form_class = AdviceForm

    def get_form_valid_message(self):
        return _("{0} updated!").format(self.object)


class AdviceCreate(FormValidMessageMixin, UserFormKwargsMixin, LoginRequiredMixin, CreateView):
    model = Advice
    form_class = AdviceForm

    def get_form_valid_message(self):
        return _("{0} created!").format(self.object)


class AdviceDelete(PermissionMixin, DeleteView):
    model = Advice
    success_url = reverse_lazy('registers:list')
    success_message = _("{__unicode__} deleted!")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.visible = False
        self.object.save()
        messages.add_message(request, messages.SUCCESS, self.get_success_message())
        return HttpResponseRedirect(success_url)


class AdviceDetail(PermissionMixin, DetailView):
    model = Advice

poradnia/advicer/templates/advicer/_sidebar.html
{% load i18n %}
{% if request.user.is_authenticated and request.user.is_staff %}
    <div class="block-list">
        <div class="block-list-header">{% trans 'Register' %}</div>
        <ul class="block-list-list">
            <li class="block-list-item">
                <a href="{% url 'advicer:list' %}?page=1"><i class="fas fa-chart-area"></i> {% trans 'Advice list' %}
                </a>
            </li>
            <li class="block-list-item">
                <a href="{% url 'advicer:table' %}"><i
                        class="fas fa-book"></i> {% trans 'Advice table' %}</a>
            </li>
        </ul>
    </div>
{% endif %}

poradnia/advicer/templates/advicer/advice_confirm_delete.html
{% extends 'advicer/advice_form.html' %}
{% load i18n %}
{% block breadcrumbs_rows %}
    <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
    <li class="active">{% trans 'Confirm delete' %}</li>
{% endblock %}
{% block form %}
    <form method="post">
        <div class="form-actions">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">
                <i class="fas fa-trash-can"></i>{% blocktrans %}Delete{{ object }}{% endblocktrans %}
            </button>
            <button class="btn" href="{{ object.get_absolute_url }}">{% trans 'Cancel' %}</button>
        </div>
    </form>
{% endblock %}

poradnia/advicer/templates/advicer/advice_detail.html
{% extends 'advicer/base.html' %}
{% load i18n humanize users_tags %}
{% block title %}{{ object }} - {{ block.super }}{% endblock %}
{% block breadcrumbs_rows %}
    <li class="active">{{ object }}</a>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <h1 class="pull-left">{{ object }}</h1>
            <div class="btn-group pull-right">
                <a href="{% url 'advicer:update' pk=object.pk %}" class="btn btn-primary">
                    <i class="fas fa-pencil"></i> {% trans 'Edit' %}
                </a>
                <a href="{% url 'advicer:delete' pk=object.pk %}" class="btn btn-danger">
                    <i class="fas fa-trash-can"></i> {% trans 'Delete' %}
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans 'Statistic data' %}</div>
                <table class="table">

                    <tr>
                        <td>{% trans 'Case' %}</td>
                        <td>
                        {% if object.case %}
                            <a href="{{ object.case.get_absolute_url }}">{{ object.case }}</a>
                        {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <td>{% trans 'Issues' %}</td>
                        <td>
                        {% if object.issues.all %}
                            {% for obj in object.issues.all %}
                                {{ obj }}{% if not forloop.last %}<br>{% endif %}
                            {% endfor %}
                        {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <td>{% trans 'Area' %}</td>
                        <td>
                            {% if object.area.all %}
                                {% for obj in object.area.all %}
                                    {{ obj }}{% if not forloop.last %}<br>{% endif %}
                                {% endfor %}
                            {% endif %}
                        </td>
                    </tr>

                    <tr>
                        <td>{% trans 'Kind of person' %}</td>
                        <td>
                            {{ object.person_kind | default:"---" }}
                        </td>
                    </tr>

                    <tr>
                        <td>{% trans 'Kind of istitution' %}</td>
                        <td>{{ object.institution_kind | default:"---" }}</td>
                    </tr>

                    <tr>
                        <td>{% trans 'Unit of administrative division' %}</td>
                        <td>{{ object.jst | default:"---" }}</td>
                    </tr>

                    <tr>
                        <td>{% trans 'Comment' %}</td>
                        <td>{{ object.comment | linebreaks }}</td>
                    </tr>

                    <tr>
                        <td>{% trans 'We helped?' %}</td>
                        <td>{{ object.helped|yesno:_("Yes,No") }}</td>
                    </tr>

                </table>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans 'Details' %}</div>
                <table class="table">
                        <tr>
                            <td>{% trans 'Grant on' %}</td>
                            <td>
                            {% if object.grant_on %}
                                <time datetime="{{ object.grant_on|date:'Y-m-d h:m:sT' }}">{{ object.grant_on |naturaltime }}</time>
                            {% endif %}
                            </td>
                        </tr>
                    <tr>
                        <td>{% trans 'Created' %}</td>
                        <td><img src="{% get_avatar_url object.created_by %}">
                            {% blocktrans with object.created_by as created and object.created_on|naturaltime as created_on_natural and object.created_on|date:'Y-m-d h:m:sT' as created_on_date %}
                                {{ created }} on
                                <time datetime="{{ created_on_date }}">{{ created_on_natural }}</time>{% endblocktrans %}
                        </td>
                    </tr>

                        <tr>
                            <td>{% trans 'Modified' %}</td>
                            <td>
                            {% if object.modified_by %}
                                <img
                                    src="{% get_avatar_url object.modified_by %}">{% blocktrans with object.modified_by as modified_by and object.modified_on|naturaltime as modified_on_natural and object.modified_on|date:'Y-m-d h:m:sT' as modified_on_date %}
                                {{ modified_by }} on
                                <time datetime="{{ modified_on_date }}">{{ modified_on_natural }}</time>{% endblocktrans %}
                            {% endif %}
                            </td>
                        </tr>
                    <tr>
                        <td>{% trans 'Advicer' %}</td>
                        <td>{{ object.advicer }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        {% if object.attachment_set.all %}
            <h2>{% trans 'Attachments' %}</h2>
            <ul>
                {% for object in object.attachment_set.all %}
                    <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

poradnia/advicer/templates/advicer/advice_filter.html
{% extends 'advicer/base.html' %}
{% load humanize i18n crispy_forms_tags bootstrap_pagination %}
{% block breadcrumbs_rows %}
    <li class="active">{% trans 'Advice index' %}</li>
    <div class="pull-right">
        <a href="{% url 'advicer:create' %}" class="btn btn-success"><i
                class="fas fa-pencil"></i> {% trans 'Add' %}</a>
    </div>
{% endblock %}
{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-md-12 col-sm-12">
                {% crispy filter.form %}
                {% if object_list %}
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>{% trans 'Creation date' %}</th>
                                    <th>{% trans 'Created by' %}</th>
                                    <th>{% trans 'Advicer' %}</th>
                                    <th>{% trans 'Subject' %}</th>
                                    <th>{% trans 'Client of case' %}</th>
                                    <th>{% trans 'Case' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in object_list %}
                                    <tr>
                                        <td>
                                            <time datetime="{{ object.created_on|date:'Y-m-d h:m:sT' }}">{{ object.created_on|naturaltime }}</time>
                                        </td>
                                        <td {% if object.created_by_id == object.advicer_id %} colspan="2"
                                                                                            style="text-align: center"{% endif %}>{{ object.created_by }}</td>
                                        {% if object.created_by_id != object.advicer_id %}
                                            <td>{{ object.advicer }}</td>
                                        {% endif %}
                                        <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
                                        {% if object.case %}
                                            <td><a href="{{ object.case.client.get_absolute_url }}">{{ object.case.client }}</a>
                                            <td><a href="{{ object.case.get_absolute_url }}">{{ object.case }}</a></td>
                                        {% else %}
                                            <td>-</td>
                                            <td>-</td>
                                        {% endif %}
                                    </tr>
                                    <tr>
                                        <td colspan="6">{{ object.comment }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div class="text-center">
                                {% bootstrap_paginate page_obj show_first_last="true" %}
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="row">
                        <div class="col-md-12">
                            <p>{% url 'advicer:create' as create_url %}{% blocktrans %}There is no Advice records.
                                <a href="{{ create_url }}">Add one</a> of these! {% endblocktrans %}</p>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>

{% endblock %}

{% block extra_css %}
    {{ block.super }}
    <style>
        select#id_person_kind, select#id_area, select#id_issues, select#id_institution_kind, select#id_helped {
            width: 100%;
        }
    </style>

{% endblock %}

poradnia/advicer/templates/advicer/advice_form.html
{% extends 'advicer/base.html' %}
{% load crispy_forms_tags i18n %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        ;(function($) {
            $(function () {
                $('form tbody tr').formset({
                    'deleteText': '{% trans "remove"%}',
                    'addText': '{% trans "add another"%}',
                    prefix: 'attachment_set'
                });
            })
        })(jQuery);
    </script>
{% endblock %}

{% block breadcrumbs_rows %}
    {% if object %}
        <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
        <li class="active">{% trans 'Update' %}</li>
    {% else %}
        <li class="active">{% trans 'Add' %}</li>
    {% endif %}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-12 col-md-12 col-sm-12">
            {% if object %}<h1>{{ object }}</h1>{% endif %}
            {% block form %}
                <form class="{{ form.helper.form_class }}" enctype="multipart/form-data" method="POST">
                    {% crispy form %}
                    {% crispy formset %}
                </form>
            {% endblock %}
        </div>
    </div>
</div>

{% endblock %}

poradnia/advicer/templates/advicer/advice_table.html
{% extends "base.html" %}
{% load static %}
{# {% load bootstrap4 %} #}
{% load i18n %}


{% block content %}

<style>
    input[type=search] {
        width: 400px; /* set the desired min-width value */
    }
    input[type=text] {
        width: 60px; /* set the desired min-width value */
    }
    /* Set the maximum width of the select element */
    select {
        width: 60px;
        height: 26px; /* adjust height value to input[type=search]*/
    }
    /* Allow the select element to wrap its options */
    select option {
        white-space: normal;
    }
</style>

<h3> {% trans 'Advice Table' %}</h3>

<div id="modal-popup" class="modal fade" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" style="width:1000px;" ></div>
    </div>
</div>

<div id="tableWrapper">
    <!-- TODO add colvis button and functionality -->
    <!-- TODO fix column invisible column sorting buttons -->
    <div class="col-sm-1 filters">
        <br><br><br><br>
        <h4>{% trans 'Filters' %}:</h4><br>
        <div class="row">
            <label>{% trans 'Helped? (col. H?)' %}:</label><br>
            <input type="checkbox" id="helped_yes" name="check_helped_yes" checked>
            <label for="helped_yes" class="small">{% trans 'Yes' %} &nbsp;
                <span class="fas fa-check" style="color: green;"></span>
            </label><br>
            <input type="checkbox" id="helped_no" name="check_helped_no" checked>
            <label for="helped_no" class="small">{% trans 'No' %} &nbsp;
                <span class="fas fa-xmark" style="color: red;"></span>
            </label><br>
            <input type="checkbox" id="helped_blank" name="check_helped_blank" checked>
            <label for="helped_blank" class="small">{% trans 'Unknown' %}  &nbsp;
                <span class="fas fa-question"></span>
            </label><br>
            <br><br>
        </div>
        <div class="row">
            <label>{% trans 'Visible (col. V.)' %}:</label><br>
            <input type="checkbox" id="visible_yes" name="check_visible_yes" checked>
            <label for="visible_yes" class="small">{% trans 'Yes' %}  &nbsp;
                <span class="fas fa-check" style="color: green;"></span>
            </label><br>
            <input type="checkbox" id="visible_no" name="check_visible_no" checked>
            <label for="visible_no" class="small">{% trans 'No' %}   &nbsp;
                <span class="fas fa-xmark" style="color: red;"></span>
            </label><br>
            <br><br>
        </div>
    </div>
    <div class="table-responsive">
        <table id="datatable_advices" width="100%" class="table table-bordered compact">
            <!-- table-striped  nowrap-->
        </table>
    </div>
</div>

{% endblock %}

poradnia/advicer/templates/advicer/base.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Advice list' %} - {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="{% url 'advicer:list' %}">{% trans 'Advice list' %}</a></li>
        {% block breadcrumbs_rows %}{% endblock %}
    </ol>
{% endblock %}