config/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseServerError
from django.template import loader
from django.urls import include, path
from django.views.generic import TemplateView

logger = logging.getLogger(__name__)

admin.autodiscover()

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("navsearch/", include("poradnia.navsearch.urls", namespace="navsearch")),
    # User management
    path("uzytkownik/klucze", include("poradnia.keys.urls", namespace="keys")),
    path("uzytkownik/", include("poradnia.users.urls", namespace="users")),
    path("konta/", include("allauth.urls")),
    # Poradnia
    path("sprawy/", include("poradnia.cases.urls", namespace="cases")),
    path("listy/", include("poradnia.letters.urls", namespace="letters")),
    path("wydarzenia/", include("poradnia.events.urls", namespace="events")),
    path("porady/", include("poradnia.advicer.urls", namespace="advicer")),
    path("uwagi/", include("poradnia.tasty_feedback.urls", namespace="tasty_feedback")),
    path("sprawy_sadowe/", include("poradnia.judgements.urls", namespace="judgements")),
    path("teryt/", include("poradnia.teryt.urls", namespace="teryt")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt")),
    path(
        "strony/regulamin-poradnictwa/",
        TemplateView.as_view(template_name="pages/terms.html"),
        name="terms",
    ),
    path(
        "strony/polityka-prywatnosci/",
        TemplateView.as_view(template_name="pages/privacy.html"),
        name="privacy",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    except ImportError:
        logger.warning("Could not import debug_toolbar.")


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """

    t = loader.get_template("500.html")
    return HttpResponseServerError(t.render({"request": request}))

poradnia/cases/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.CaseListView.as_view(), name="list"),
    path(
        "table/",
        views.CaseTableView.as_view(),
        name="table",
    ),
    path(
        "case_table_ajax_data/",
        views.CaseAjaxDatatableView.as_view(),
        name="case_table_ajax_data",
    ),
    path("sprawa-<int:pk>/edytuj/", views.CaseUpdateView.as_view(), name="edit"),
    path("sprawa-<int:pk>/zamknij/", views.CaseCloseView.as_view(), name="close"),
    path("sprawa-<int:pk>/scal/", views.CaseMergeView.as_view(), name="merge"),
    path(
        "sprawa-<int:pk>/uprawnienia/",
        views.UserPermissionCreateView.as_view(),
        name="permission_add",
    ),
    path(
        "sprawa-<int:pk>/uprawnienia-<username>/",
        views.UserPermissionUpdateView.as_view(),
        name="permission_update",
    ),
    path(
        "sprawa-<int:pk>/uprawnienia-<username>/~remove",
        views.UserPermissionRemoveView.as_view(),
        name="permission_remove",
    ),
    path(
        "sprawa-<int:pk>/uprawnienia/przyznaj/",
        views.CaseGroupPermissionView.as_view(),
        name="permission_grant",
    ),
    path("sprawa-<int:pk>/", views.CaseDetailView.as_view(), name="detail"),
    path("~autocomplete", views.CaseAutocomplete.as_view(), name="autocomplete"),
]

app_name = "poradnia.cases"

poradnia/events/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("sprawa-<int:case_pk>/", views.EventCreateView.as_view(), name="add"),
    path("wydarzenie-<int:pk>", views.EventUpdateView.as_view(), name="edit"),
    path(
        "<int:year>-<int:month>",
        views.CalendarEventView.as_view(month_format="%m"),
        name="calendar",
    ),
    path("", views.CalendarListView.as_view(), name="calendar"),
    path("ical/", views.ICalendarView.as_view(), name="calendar_ical"),
    path("table/", views.EventTableView.as_view(), name="table"),
    path(
        "events_table_ajax_data/",
        views.EventAjaxDatatableView.as_view(),
        name="events_table_ajax_data",
    ),
]

app_name = "poradnia.events"

poradnia/keys/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.KeyListView.as_view(), name="list"),
    path("<int:pk>/", views.KeyDetailView.as_view(), name="details"),
    path("<int:pk>/usun/", views.KeyDeleteView.as_view(), name="delete"),
    path("stworz/", views.KeyCreateView.as_view(), name="create"),
]

app_name = "poradnia.keys"

poradnia/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.http import HttpResponseServerError
from django.template import loader
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^navsearch/', include('navsearch.urls', namespace="navsearch")),

    # User management
    url(r'^uzytkownik/klucze', include('keys.urls', namespace="keys")),
    url(r'^uzytkownik/', include("users.urls", namespace="users")),
    url(r'^konta/', include('allauth.urls')),

    # Flatpages
    url(r'^strony/', include('django.contrib.flatpages.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    # Poradnia
    url(r'^sprawy/', include('cases.urls', namespace='cases')),
    url(r'^listy/', include('letters.urls', namespace='letters')),
    url(r'^wydarzenia/', include('events.urls', namespace='events')),
    url(r'^porady/', include('advicer.urls', namespace='advicer')),
    url(r'^statystyki/', include('stats.urls', namespace='stats')),
    # Utils
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^uwagi/', include('tasty_feedback.urls', namespace='tasty_feedback')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """

    t = loader.get_template('500.html')  # You need to create a 500.html template.
    return HttpResponseServerError(t.render({
        'request': request,
    }))

poradnia/navsearch/models.py
# Create your models here.

poradnia/advicer/forms.py
from atom.ext.crispy_forms.forms import (
    FormHorizontalMixin,
    HelperMixin,
    SingleButtonMixin,
)
from atom.forms import AuthorMixin
from braces.forms import UserKwargModelFormMixin
from crispy_forms.layout import Fieldset, Layout
from dal import autocomplete
from django import forms
from django.forms import ModelForm
from django.utils.timezone import now
from django.utils.translation import gettext as _

from poradnia.cases.models import Case

from .models import Advice, Attachment


class AdviceForm(
    UserKwargModelFormMixin,
    FormHorizontalMixin,
    SingleButtonMixin,
    AuthorMixin,
    ModelForm,
):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_method = "post"
        self.fields["grant_on"].initial = now()
        self.fields["case"].queryset = Case.objects.for_user(self.user).all()
        self.fields["case"].help_text = _(
            "Select from poradnia.cases which do " "you have a permission"
        )
        self.helper.layout = Layout(
            Fieldset(
                _("Statistic data"),
                "case",
                "issues",
                "area",
                "person_kind",
                "institution_kind",
                "jst",
                "helped",
            ),
            Fieldset(_("Details"), "subject", "grant_on", "advicer", "comment"),
        )

    class Meta:
        model = Advice
        fields = [
            "case",
            "subject",
            "grant_on",
            "issues",
            "area",
            "person_kind",
            "institution_kind",
            "advicer",
            "comment",
            "helped",
            "jst",
        ]
        widgets = {
            "jst": autocomplete.ModelSelect2(url="teryt:community-autocomplete"),
            "case": autocomplete.ModelSelect2(url="cases:autocomplete"),
            "issues": autocomplete.ModelSelect2Multiple(
                url="advicer:issue-autocomplete"
            ),
            "area": autocomplete.ModelSelect2Multiple(url="advicer:area-autocomplete"),
        }


class AttachmentForm(HelperMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_tag = False
        self.helper.form_method = "post"

    class Meta:
        model = Attachment
        fields = ["attachment"]

poradnia/cases/forms.py
from atom.ext.crispy_forms.forms import (
    FormHorizontalMixin,
    HelperMixin,
    SingleButtonMixin,
)
from braces.forms import UserKwargModelFormMixin
from crispy_forms.layout import Submit
from dal import autocomplete
from django import forms
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from guardian.shortcuts import assign_perm

from ..letters.models import Letter
from ..records.models import Record
from .models import Case, PermissionGroup


class CaseForm(
    UserKwargModelFormMixin, FormHorizontalMixin, SingleButtonMixin, forms.ModelForm
):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "instance" in kwargs:
            self.helper.form_action = kwargs["instance"].get_edit_url()

    def save(self, commit=True, *args, **kwargs):
        obj = super().save(commit=False, *args, **kwargs)
        if obj.pk:  # old
            obj.modified_by = self.user
            if obj.status == Case.STATUS.assigned:
                obj.send_notification(
                    actor=self.user,
                    user_qs=obj.get_users_with_perms().filter(is_staff=True),
                    verb="updated",
                )
        else:  # new
            obj.send_notification(
                actor=self.user,
                user_qs=obj.get_users_with_perms().filter(is_staff=True),
                verb="created",
            )
            obj.created_by = self.user
        if commit:
            obj.save()
        return obj

    class Meta:
        model = Case
        fields = ("name", "status", "has_project")


class CaseGroupPermissionForm(HelperMixin, forms.Form):
    action_text = _("Grant")
    user = forms.ModelChoiceField(
        queryset=None,
        required=True,
        widget=autocomplete.ModelSelect2("users:autocomplete"),
        label=_("User"),
    )
    group = forms.ModelChoiceField(
        queryset=PermissionGroup.objects.all(), label=_("Permissions group")
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        self.case = kwargs.pop("case")
        super().__init__(*args, **kwargs)
        self.fields["user"].queryset = get_user_model().objects.for_user(self.user)
        self.helper.form_class = "form-inline"
        self.helper.layout.append(Submit("grant", _("Grant")))

        self.helper.form_action = reverse(
            "cases:permission_grant", kwargs={"pk": str(self.case.pk)}
        )

    def assign(self):
        perms = list(self.cleaned_data["group"].permissions.all())
        self.cleaned_data["user"].caseuserobjectpermission_set.filter(
            content_object=self.case
        ).exclude(permission__in=perms).delete()

        for perm in perms:
            assign_perm(perm, self.cleaned_data["user"], self.case)
        self.case.update_status()
        self.case.send_notification(
            actor=self.user,
            verb="grant_group",
            action_object=self.cleaned_data["user"],
            action_target=self.cleaned_data["group"],
            user_qs=self.case.get_users_with_perms().filter(is_staff=True),
        )


class CaseCloseForm(UserKwargModelFormMixin, HelperMixin, forms.ModelForm):
    # skip user notification, code left for potential future use
    # notify = forms.BooleanField(required=False, label=_("Notify user"))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.add_input(Submit("action", _("Close"), css_class="btn-primary"))

        if "instance" in kwargs:
            self.helper.form_action = kwargs["instance"].get_close_url()

    def save(self, commit=True, *args, **kwargs):
        obj = super().save(commit=False, *args, **kwargs)
        # skip user notification
        # obj.close(actor=self.user, notify=self.cleaned_data["notify"])
        obj.close(actor=self.user, notify=False)
        if commit:
            obj.save()
        return obj

    class Meta:
        model = Case
        fields = ()


class CaseMergeForm(UserKwargModelFormMixin, HelperMixin, forms.ModelForm):
    target = forms.ModelChoiceField(
        label=_("Destination case"),
        queryset=Case.objects.none(),
        required=True,
        widget=autocomplete.ModelSelect2(url="cases:autocomplete"),
        help_text=_(
            "The selected case will receive all letters, "
            + "events, etc. from the current case."
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.add_input(Submit("action", _("Merge"), css_class="btn-primary"))
        self.fields["target"].queryset = Case.objects.for_user(self.user).all()

        self.helper.form_action = reverse(
            "cases:merge", kwargs={"pk": kwargs["instance"].pk}
        )

    def create_letter(self, case):
        target = self.cleaned_data["target"]
        source = self.instance
        msg = Letter.objects.create(
            case=case,
            genre=Letter.GENRE.comment,
            created_by=self.user,
            created_by_is_staff=self.user.is_staff,
            text=_("Case #{source} have been merged with case #{target}").format(
                source=source.pk, target=target.pk
            ),
            status=Letter.STATUS.staff,
        )
        msg.send_notification(actor=self.user, verb="drop_a_note")

    def save(self, *args, **kwargs):
        target = self.cleaned_data["target"]
        source = self.instance
        Record.objects.filter(case=source).move(target)
        self.create_letter(target)
        self.create_letter(source)
        source.close(actor=self.user, notify=False)
        source.save()
        return source

    class Meta:
        model = Case
        fields = ()

poradnia/events/forms.py
from atom.ext.crispy_forms.forms import FormHorizontalMixin, SingleButtonMixin
from atom.forms import AuthorMixin
from django import forms
from django.urls import reverse

from poradnia.letters.forms import PartialMixin
from poradnia.users.models import User

from .models import Event


class EventForm(
    PartialMixin, AuthorMixin, FormHorizontalMixin, SingleButtonMixin, forms.ModelForm
):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        self.case = kwargs.pop("case")
        super().__init__(*args, **kwargs)
        self.helper.form_action = reverse(
            "events:add", kwargs={"case_pk": self.case.pk}
        )
        if kwargs.get("instance", False):
            self.helper.form_action = kwargs["instance"].get_edit_url()

    def save(self, commit=True, *args, **kwargs):
        obj = super().save(commit=False, *args, **kwargs)
        created = obj.pk is None
        obj.case = self.case
        obj.save()
        verb = "created" if created else "updated"
        obj.send_notification(
            actor=self.user,
            user_qs=(
                User.objects.filter(is_staff=True).distinct()
                & self.case.get_users_with_perms()
            ),
            verb=verb,
        )
        return obj

    class Meta:
        # Set this form to use the User model.
        model = Event
        fields = ("deadline", "completed", "public", "time", "text")
        widgets = {"time": forms.DateTimeInput(attrs={"autocomplete": "off"})}

poradnia/feedback_custom/forms.py
from atom.ext.crispy_forms.forms import FormHorizontalMixin, SingleButtonMixin

from poradnia.tasty_feedback.forms import FeedbackForm


class CustomFeedbackForm(FormHorizontalMixin, SingleButtonMixin, FeedbackForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_tag = False

poradnia/keys/forms.py
from atom.ext.crispy_forms.forms import SingleButtonMixin
from braces.forms import UserKwargModelFormMixin
from django.forms import ModelForm

from .models import Key


class KeyForm(UserKwargModelFormMixin, SingleButtonMixin, ModelForm):
    class Meta:
        model = Key
        fields = ["description"]

    def save(self, commit=True, *args, **kwargs):
        obj = super().save(commit=False, *args, **kwargs)
        obj.user = self.user
        if commit:
            obj.save()
        return obj

poradnia/templates/pages/about.html
{% extends "base.html" %}

poradnia/templates/pages/home.html
{% extends "base.html" %}
{% load tinycontent_tags %}
{% block content %}
    <div class="row">
        <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-1">
            {% tinycontent 'home:start' %}
                <a href="http://siecobywatelska.pl/wlacz-sie-5min/#wspieraj_siec" class="support-button pull-right">Wesprzyj nas
                    finansowo</a>
                <h1>Pomagamy Ci skutecznie korzystać z&nbsp;Twoich praw</h1>
                <h2>Jak udzielamy pomocy prawnej?</h2>

                <p>Udzielamy ponad 1000 konsultacji prawnych rocznie. Aby sprawniej Ci pomagać, stworzyliśmy stronę, na której w
                    tej chwili się znajdujesz.</p>

                <p>Specjalizujemy się w takich tematach, jak dostęp do informacji publicznej, fundusz sołecki i&nbsp;wpływanie
                    na decyzje rządzących. W tych obszarach mamy pewność, że porada którą otrzymujesz opiera się na
                    doświadczeniu i&nbsp;bogatej, przemyślanej wiedzy.</p>
            {% endtinycontent %}
            {% if requests.user.is_anonymous %}
                {% tinycontent 'home:anonymous' %}
                    <p>Aby zgłosić nam problemy, który chcesz rozwiązać, <a href="{% url 'account_signup' %}">zarejestruj
                        się</a> lub <a href="{% url 'account_login' %}">zaloguj</a> i&nbsp;użyj <a
                            href="{% url 'letters:add' %}">formularza dla "nowej sprawy"</a>. Jeżeli chcesz odwołać się do
                        wcześniejszej korespondencji z&nbsp;nami, dotyczącej innych problemów - skorzystaj z&nbsp;„<a
                                href="{% url 'cases:list' %}">wykazu spraw</a>”.</p>
                {% endtinycontent %}
            {% else %}
                {% tinycontent 'home:user' %}
                    <p>Aby zgłosić nam problem, który chcesz rozwiązać, <a href="{% url 'letters:add' %}">użyj formularza dla
                        "nowej sprawy"</a>. Jeżeli chcesz odwołać się do wcześniejszej korespondencji z&nbsp;nami, dotyczącej
                        innych problemów - skorzystaj z&nbsp;„<a href="{% url 'cases:list' %}">wykazu spraw</a>”.
                    </p>
                {% endtinycontent %}
            {% endif %}
            {% tinycontent 'home:end' %}
                <div class="freatures">
                    <div class="freatures__freature">
                        <div class="freature__icon"><i class="fa-solid fa-binoculars"></i></div>
                        <div class="freature__title">Sprawdzamy</div>
                        <div class="freature__description">Od lat sprawdzamy jak w praktyce funkcjonują gwarancje konstytucyjne
                            i&nbsp;przepisy ustawy o dostępie do informacji publicznej oraz o funduszu sołeckim, a także
                            rozwiązania dotyczące skarg i&nbsp;wniosków oraz kontrola w samorządzie.
                        </div>
                    </div>
                    <div class="freatures__freature">
                        <div class="freature__icon"><i class="fas fa-book"></i></div>
                        <div class="freature__title">Uczymy</div>
                        <div class="freature__description">Przeprowadziliśmy kilkaset spotkań i&nbsp;szkoleń dla obywatelek i&nbsp;obywateli,
                            na temat tego jak korzystać z&nbsp;prawa i&nbsp;skutecznie wpływać na działania władz.
                        </div>
                    </div>
                    <div class="freatures__freature">
                        <div class="freature__icon"><i class="fa-solid fa-building-columns"></i></div>
                        <div class="freature__title">Chodzimy do sądu</div>
                        <div class="freature__description">Wtedy, gdy instytucje nie stosują prawa, szukamy sprawiedliwości w
                            sądach. Przeprowadziliśmy kilkaset spraw sądowych, wiele z&nbsp;nich wygrywając.
                        </div>
                    </div>
                </div>

                <h2>Kim jesteśmy?</h2>

                <p>Sieć Obywatelska Watchdog Polska to niezależna, apolityczna i&nbsp;niedochodowa organizacja pożytku
                    publicznego o charakterze organizacji strażniczej i&nbsp;think-do-thanku.</p>

                <p>Stoimy na straży prawa do informacji. Postrzegamy je nie tylko jako warunek dobrego państwa, ale przede
                    wszystkim jako jedno z&nbsp;praw człowieka, które chroni ludzką godność, daje wolność wyrażania opinii i&nbsp;bezpieczeństwo
                    przed nadużyciami władzy.</p>

                <p>Wzmacniamy w obywatelach poczucie, że mają prawo dowiadywać się, jak funkcjonują władze oraz instytucje
                    publiczne, a także wpływać na podejmowane przez nie decyzje i&nbsp;sposób gospodarowania publicznym
                    majątkiem (m. in. pieniędzmi z&nbsp;podatków). </p>

                <div class="support-notice text-center">
                    <p>Chcesz aby Twoje prawa były chronione, politycy mądrze wydawali Twoje pieniądze?</p>
                    <p><a href="http://siecobywatelska.pl/wlacz-sie-5min/#wspieraj_siec" class="support-button">Wesprzyj nas
                        finansowo</a></p>
                    <p style="font-size: 2.3em;">lub <a href="http://siecobywatelska.pl/wlacz-sie-5min/#scroll">włącz się w
                        nasze działania</a>.</p>
                </div>
            {% endtinycontent %}
        </div>
    </div>

{% endblock %}

poradnia/templates/pages/privacy.html
{% extends 'base.html' %}
{% load tinycontent_tags %}
{% block title %}Polityka prywatności - {{ block.super }}{% endblock %}
{% block content %}
    <h1>Polityka prywatności</h1>
    {% tinycontent 'privacy' %}
    TODO
    {% endtinycontent %}
{% endblock %}

poradnia/templates/pages/terms.html
{% extends 'base.html' %}
{% load tinycontent_tags %}
{% block title %}Regulamin poradnictwa - {{ block.super }}{% endblock %}
{% block content %}
<h1>Regulamin poradnictwa</h1>
{% tinycontent 'terms' %}
TODO
{% endtinycontent %}
{% endblock %}

poradnia/templates/pages/user.html
{{ request.user }}