config/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseServerError
from django.template import loader
from django.urls import include, path
from django.views.generic import TemplateView

logger = logging.getLogger(__name__)

admin.autodiscover()

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("navsearch/", include("poradnia.navsearch.urls", namespace="navsearch")),
    # User management
    path("uzytkownik/klucze", include("poradnia.keys.urls", namespace="keys")),
    path("uzytkownik/", include("poradnia.users.urls", namespace="users")),
    path("konta/", include("allauth.urls")),
    # Poradnia
    path("sprawy/", include("poradnia.cases.urls", namespace="cases")),
    path("listy/", include("poradnia.letters.urls", namespace="letters")),
    path("wydarzenia/", include("poradnia.events.urls", namespace="events")),
    path("porady/", include("poradnia.advicer.urls", namespace="advicer")),
    path("uwagi/", include("poradnia.tasty_feedback.urls", namespace="tasty_feedback")),
    path("sprawy_sadowe/", include("poradnia.judgements.urls", namespace="judgements")),
    path("teryt/", include("poradnia.teryt.urls", namespace="teryt")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt")),
    path(
        "strony/regulamin-poradnictwa/",
        TemplateView.as_view(template_name="pages/terms.html"),
        name="terms",
    ),
    path(
        "strony/polityka-prywatnosci/",
        TemplateView.as_view(template_name="pages/privacy.html"),
        name="privacy",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    except ImportError:
        logger.warning("Could not import debug_toolbar.")


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """

    t = loader.get_template("500.html")
    return HttpResponseServerError(t.render({"request": request}))

poradnia/judgements/urls.py
from django.urls import path

from poradnia.judgements import views

urlpatterns = [
    path("~create-<int:case_pk>", views.CourtCaseCreateView.as_view(), name="create"),
    path(
        "courtcase-<int:pk>/~update", views.CourtCaseUpdateView.as_view(), name="update"
    ),
    path(
        "courtcase-<int:pk>/~delete", views.CourtCaseDeleteView.as_view(), name="delete"
    ),
]

app_name = "poradnia.judgements"

poradnia/letters/urls.py
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt

from . import views

urlpatterns = [
    path("webhook", csrf_exempt(views.ReceiveEmailView.as_view()), name="webhook"),
    path("rejestr", views.LetterListView.as_view(), name="list"),
    path(
        "table/",
        views.cbv.LetterTableView.as_view(),
        name="table",
    ),
    path(
        "letters_table_ajax_data/",
        views.cbv.LetterAjaxDatatableView.as_view(),
        name="letters_table_ajax_data",
    ),
    path("sprawa-<int:case_pk>/", views.add, name="add"),
    path(
        "sprawa-<int:case_pk>/list-<int:letter_pk>/zalaczniki",
        views.StreamAttachmentView.as_view(),
        name="attachments_zip",
    ),
    path(
        "sprawa-<int:case_pk>/list-<int:letter_pk>/zalacznik/<int:pk>",
        views.DownloadAttachmentView.as_view(),
        name="attachment_download",
    ),
    path("<int:pk>/wyslij/", views.send, name="send"),
    path("<int:pk>/edytuj/", views.LetterUpdateView.as_view(), name="edit"),
    path("<int:pk>/", views.send, name="detail"),
    path("", views.NewCaseCreateView.as_view(), name="home"),
    path("", views.NewCaseCreateView.as_view(), name="add"),
    path("tinymce/", include("tinymce.urls")),
]

app_name = "poradnia.letters"

poradnia/users/urls.py
from django.urls import path, re_path

from poradnia.users import views

urlpatterns = [
    path("", views.UserListView.as_view(), name="list"),
    re_path(r"^~przekieruj/$", views.UserRedirectView.as_view(), name="redirect"),
    re_path(
        r"^(?P<username>[\w.@+-]+)/$",
        views.UserDetailView.as_view(),
        name="detail",
    ),
    path("info/<username>/", views.UserInfoView.as_view(), name="user_info"),
    re_path(
        r"^(?P<username>[\w.@+-]+)/~deassign/$",
        views.UserDeassignView.as_view(),
        name="deassign",
    ),
    re_path(r"^~aktualizuj/$", views.UserUpdateView.as_view(), name="update"),
    re_path(r"^~profil/$", views.ProfileUpdateView.as_view(), name="profile"),
    re_path(
        r"^~autocomplete/$",
        views.UserAutocomplete.as_view(),
        name="autocomplete",
    ),
]

app_name = "poradnia.users"

poradnia/users/forms/account.py
from atom.ext.crispy_forms.forms import FormHorizontalMixin
from atom.ext.tinycontent.forms import GIODOMixin
from crispy_forms.bootstrap import PrependedText
from crispy_forms.layout import Layout, Submit
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _
from turnstile.fields import TurnstileField

from poradnia.utils.constants import TURNSTILE_ERROR_MESSAGES


class SignupForm(
    FormHorizontalMixin,
    GIODOMixin,
    forms.ModelForm,
):

    turnstile = TurnstileField(
        label=_(" "), error_messages=TURNSTILE_ERROR_MESSAGES, language="pl"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.label_class = "col-lg-3"
        self.helper.field_class = "col-lg-9"
        self.helper.layout = Layout(
            "first_name",
            "last_name",
            PrependedText("username", '<i class="fas fa-user"></i>'),
            PrependedText("email", "@"),
            PrependedText("password1", '<i class="fas fa-key"></i>', type="password"),
            PrependedText("password2", '<i class="fas fa-key"></i>', type="password"),
            "giodo",
            "turnstile",
        )
        self.helper.add_input(Submit("signup", _("Signup"), css_class="btn-primary"))

    class Meta:
        model = get_user_model()  # use this function for swapping user model
        fields = ["first_name", "last_name"]

    def save(self, user):
        user.save()

    def signup(self, request, user):
        pass

poradnia/users/forms/permissions.py
from atom.ext.crispy_forms.forms import SingleButtonMixin
from dal import autocomplete
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _
from guardian.forms import BaseObjectPermissionsForm, UserObjectPermissionsForm
from guardian.shortcuts import assign_perm, remove_perm


class PermissionsTranslationMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["permissions"].choices = [
            (key, _(value)) for key, value in self.fields["permissions"].choices
        ]


class TranslatedUserObjectPermissionsForm(
    SingleButtonMixin, PermissionsTranslationMixin, UserObjectPermissionsForm
):
    pass


class TranslatedManageObjectPermissionForm(
    SingleButtonMixin, PermissionsTranslationMixin, BaseObjectPermissionsForm
):
    users = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.none(),
        required=True,
        widget=autocomplete.ModelSelect2Multiple(url="users:autocomplete"),
        label=_("Users"),
    )

    def __init__(self, *args, **kwargs):
        self.actor = kwargs.pop("actor")
        self.staff_only = kwargs.pop("staff_only", False)
        super().__init__(*args, **kwargs)
        self.fields["users"].queryset = (
            get_user_model().objects.for_user(self.actor).all()
        )

    def are_obj_perms_required(self):
        return True

    def save_obj_perms(self):
        for user in self.cleaned_data["users"]:
            perms = self.cleaned_data[self.get_obj_perms_field_name()]
            model_perms = [c[0] for c in self.get_obj_perms_field_choices()]

            to_remove = set(model_perms) - set(perms)
            for perm in to_remove:
                remove_perm(perm, user, self.obj)

            for perm in perms:
                assign_perm(perm, user, self.obj)

poradnia/users/forms/users.py
from atom.ext.crispy_forms.forms import FormHorizontalMixin, SingleButtonMixin
from braces.forms import UserKwargModelFormMixin
from django import forms
from django.contrib.auth import get_user_model
from django.forms import Textarea

from ..models import Profile


class UserForm(FormHorizontalMixin, SingleButtonMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance or self.instance and not self.instance.is_staff:
            del self.fields["codename"]
            self.helper.layout.fields.remove("codename")

    class Meta:
        # Set this form to use the User model.
        model = get_user_model()

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name", "picture", "codename")


class ProfileForm(
    UserKwargModelFormMixin, FormHorizontalMixin, SingleButtonMixin, forms.ModelForm
):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # dynamically exclude event_reminder_time if user is not a staff member
        if not self.user.is_staff:
            del self.fields["event_reminder_time"]
            self.helper.layout.fields.remove("event_reminder_time")
            del self.fields["email_footer"]
            self.helper.layout.fields.remove("email_footer")

    class Meta:
        model = Profile
        fields = ("description", "www", "event_reminder_time", "email_footer")
        widgets = {"email_footer": Textarea(attrs={"cols": 30, "rows": 4})}

poradnia/users/views.py
from atom.views import ActionMessageMixin, ActionView
from braces.views import LoginRequiredMixin, StaffuserRequiredMixin, UserFormKwargsMixin
from dal import autocomplete
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django_filters.views import FilterView

from poradnia.cases.models import Case, CaseUserObjectPermission
from poradnia.utils.mixins import ExprAutocompleteMixin

from .filters import UserFilter
from .forms import ProfileForm, UserForm
from .models import Profile, User
from .utils import PermissionMixin


class UserDetailView(PermissionRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    permission_required = "users.can_view_other"
    raise_exception = True

    def has_permission(self, *args, **kwargs):
        if self.kwargs["username"] == self.request.user.username:
            return True
        return super().has_permission(*args, **kwargs)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            url = reverse(
                "users:user_info", kwargs={"username": self.kwargs["username"]}
            )
            return HttpResponseRedirect(url)
        else:
            raise PermissionDenied


class UserInfoView(DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/user_info.html"
    fields = ["picture", "profile"]

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.only(*self.fields)


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class ProfileUpdateView(UserFormKwargsMixin, LoginRequiredMixin, UpdateView):
    form_class = ProfileForm
    model = Profile

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return Profile.objects.get_or_create(user=self.request.user)[0]


class UserListView(StaffuserRequiredMixin, PermissionMixin, FilterView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    filterset_class = UserFilter
    paginate_by = 25
    IS_STAFF_FILTER = (
        (_("All users"), {}),
        (_("Staff"), {"is_staff": True}),
        ((_("Clients"), {"is_staff": False})),
    )

    def get_is_staff_choice(self):
        if "is_staff" not in self.request.GET:
            return 0
        if not self.request.GET["is_staff"].isdigit():
            return 0
        num = int(self.request.GET["is_staff"])
        if len(self.IS_STAFF_FILTER) < num:
            return 0
        return num

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(**self.IS_STAFF_FILTER[self.get_is_staff_choice()][1])
        qs = qs.with_case_count()
        qs = qs.with_case_count_assigned()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_staff"] = dict(
            choices=enumerate(self.IS_STAFF_FILTER), selected=self.get_is_staff_choice()
        )
        return context


class UserAutocomplete(
    PermissionMixin, ExprAutocompleteMixin, autocomplete.Select2QuerySetView
):
    model = User
    search_expr = [
        "first_name__icontains",
        "last_name__icontains",
        "username__icontains",
    ]


class UserDeassignView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    ActionMessageMixin,
    ActionView,
):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    permission_required = "cases.can_assign"
    success_message = _("{subject} deassigned")
    template_name_suffix = "_deassign"
    raise_exception = True

    def get_success_url(self):
        return self.object.get_absolute_url()

    def action(self):
        self.count = int(
            Case.objects.filter(caseuserobjectpermission__user=self.object)
            .exclude(client=self.object)
            .distinct()
            .count()
        )
        CaseUserObjectPermission.objects.filter(user=self.object).exclude(
            content_object__client=self.object
        ).delete()

    def get_success_message(self):
        return _("{object} deassigned from {count} cases").format(
            object=self.object, count=self.count
        )

poradnia/users/templates/users/_sidebar.html
{% load i18n %}
<div class="block-list">
    <div class="block-list-header">{% trans 'User' %}</div>
    <ul class="block-list-list">

        {% if request.user.is_authenticated %}
            <li class="block-list-item">
                <a href="{% url 'users:detail' username=request.user.username %}"><i class="fas fa-user"></i>
                    {% blocktrans with request.user as user %}{{ user }}{% endblocktrans %}</a>
            </li>
            {% if request.user.is_staff %}
                <li class="block-list-item">
                    <a href="{% url 'users:list' %}"><i class="fas fa-users"></i> {% trans "Users list" %}</a>
                </li>
            {% endif %}
            {% if request.user.is_superuser %}
                <li class="block-list-item">
                    <a href="{% url 'admin:index' %}"><i class="fas fa-gear"></i> {% trans "App admin" %}</a>
                </li>                
            {% endif %}
            <li class="block-list-item">
                <a href="{% url 'account_logout' %}"><i class="fa-solid fa-right-from-bracket"></i> {% trans "Logout" %}</a>
            </li>
        {% else %}
            <li class="block-list-item">
                <a href="{% url 'account_signup' %}"><i class="fas fa-user"></i> {% trans "Sign Up" %}</a>
            </li>
            <li class="block-list-item">
                <a href="{% url 'account_login' %}"><i class="fa-solid fa-right-to-bracket"></i> {% trans "Log In" %}</a>
            </li>
        {% endif %}
    </ul>
</div>

poradnia/users/templates/users/base.html
{% extends 'base.html' %}
{% load i18n %}
{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="{% url 'users:list' %}">{% trans 'Users index' %}</a></li>
        {% block breadcrumbs_rows %}{% endblock %}
    </ol>
{% endblock %}

{% block content %}
    {% block users_content %}
    {% endblock %}
{% endblock %}

poradnia/users/templates/users/email_new_user.html
Rejestracja w Poradni Sieci Obywatelskiej - Watchdog Polska
Szanowny/-a {{ user }}!

Zostałeś/-aś zarejestrowany/-a w serwisie poradnictwa Stowarzyszenia Sieć Obywatelska - Watchdog Polska.

Nazwa użytkownika: {{ user.username }}
Hasło: {{ password }}

Z wyrazami szacunku,
Sieć Obywatelska - Watchdog Polska

poradnia/users/templates/users/profile_form.html
{% extends 'users/user_form.html' %}
{% load i18n %}


{% block breadcrumbs_rows %}
    <li><a href="{{ user.get_absolute_url }}">{{ user }}</a></li>
    <li class="active">{% trans 'Profile' %}</li>
{% endblock %}

{% block title %}{% trans 'Profile' %} - {{ block.super }}{% endblock %}

poradnia/users/templates/users/user_deassign.html
{% extends 'users/user_form.html' %}
{% load i18n %}
{% block breadcrumbs_rows %}
    <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
    <li class="active">{% trans 'Confirm deassign' %}</li>
{% endblock %}
{% block form %}
<p>{% blocktrans %}The operation will remove all permissions on cases for the user where they is not a client. This is an irreversible operation. Are you sure you want to do this?{% endblocktrans %}</p>
    <form method="post">
        <div class="form-actions">
            {% csrf_token %}

            <button type="submit" class="btn btn-danger">
                <i class="fa-solid fa-triangle-exclamation"></i>{% blocktrans %}Deassign {{ object }}{% endblocktrans %}
            </button>
            <button class="btn" href="{{ object.get_absolute_url }}">{% trans 'Cancel' %}</button>
        </div>
    </form>
{% endblock %}

poradnia/users/templates/users/user_detail.html
{% extends "users/base.html" %}
{% load users_tags static i18n %}
{% block title %}{% trans 'User' %}: {{ object.get_nicename }} - {{ block.super }}{% endblock %}

{% block breadcrumbs_rows %}
    <li class="active">{{ object }}</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-1">
        <img src="{% get_avatar_url object %}">
        <h3><b>{% trans 'Username' %}:</b> {{ object.username }} &nbsp; &nbsp; &nbsp;
            <b>{% trans 'Full name' %}:</b> {{ object.nicename }}</h3>
        {% if object.is_staff %}
            <p>{% trans 'Is member of staff.' %}</p>
        {% endif %}
        {% if object.profile %}
            <p><span><b>{% trans 'Description' %}:</b></span><br>
                {{ object.profile.description|linebreaksbr }}</p>
            <p><span><b>{% trans 'Email footer' %}:</b></span><br>
                {{ object.profile.email_footer|linebreaksbr }}</p>
        {% endif %}

        <!-- Start Action buttons -->

        {% if object == request.user %}
            <a class="btn btn-primary" href="{% url 'users:update' %}">
                {% trans 'About me' %}
            </a>
            <a class="btn btn-info" href="{% url 'users:profile' %}">
                {% trans 'Profile' %}
            </a>
            <a class="btn btn-info" href="{% url 'account_change_password' %}">
                <i class="fas fa-key"></i>
                {% trans 'Password change' %}
            </a>
            {% if user.is_superuser %}
            <a class="btn btn-info" href="{% url 'keys:list' %}">
                <i class="fas fa-puzzle-piece "></i>
                {% trans 'Keys' %}
            </a>
            {% endif %}
            <a class="btn btn-info" href="{% url 'cases:list' %}?client={{ object.pk }}">
                <i class="fas fa-book"></i>
                {% trans 'My cases' %}
            </a>

        {% elif perms.cases.can_assign %}
            <a class="btn btn-info" href="{% url 'cases:list' %}?client={{ object.pk }}">
                <i class="fas fa-book"></i>
                {% trans 'Client cases' %}
            </a>
            <a class="btn btn-info" href="{% url 'cases:list' %}?permission={{ object.pk }}">
                <i class="fas fa-book"></i>
                {% trans 'Assigned cases' %}
            </a>
            <a class="btn btn-info" href="{% url 'users:deassign' username=object.username%}">
                <i class="fa-solid fa-triangle-exclamation"></i>
                {% trans 'Deassign cases' %}
            </a>
        {% endif %}
        <!-- End Action buttons -->
    </div>
</div>

{% endblock content %}

poradnia/users/templates/users/user_filter.html
{% extends "users/base.html" %}
{% load static i18n users_tags crispy_forms_tags querystring_tags bootstrap_pagination %}

{% block title %}{% trans 'Users index' %}{% endblock %}

{% block breadcrumbs_rows %}
    <li class="active">{% trans 'Users index' %}</li>
{% endblock %}

{% block extra_css %}
    <style>
        .staff {
            background-color: #FF7474;
        }
        #submit-id-filter {
            margin-top: 20px;
        }
        #user-nav-tabs {
            margin-top: 10px;
        }

    </style>
{% endblock %}
{% block users_content %}
<div class="row">
    <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-1">
        <h2>{% trans 'Users' %}</h2>
        {% if not perms.users.can_view_other %}
            <p>
                {% trans "You don't have access to data of all our users. Mostly you have access to staff and own profile." %}
            </p>
        {% endif %}

        <div class="row">
            {% crispy filter.form %}
            <ul class="nav nav-tabs" id="user-nav-tabs">
                {% for key, value in is_staff.choices %}
                    <li role="presentation"{% if key == is_staff.selected %} class="active"{% endif %}><a
                            href="?{% query_update is_staff=key page='' %}">{{ value.0 }}</a></li>
                {% endfor %}
            </ul>
        </div>

        <table class="table table-condensed table-users">
            <thead>
            <tr>
                <th class="user">{% trans 'User' %}</th>
                <th class="client_cases">{% trans 'Client cases' %}</th>
                <th class="free_cases">{% trans 'Assigned cases sum' %}</th>
                {# <th class="free_cases">{% trans 'Free' %}</th> #}
                <th class="assigned_cases">{% trans 'Moderated' %}</th>
                <th class="assigned_cases">{% trans 'Active_' %}</th>
                <th class="closed_cases">{% trans 'Closed' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for user in object_list %}
                <tr {% if user.is_staff %}class="staff"{% endif %}>
                    <td>
                        <a href="{% url 'users:detail' user.username %}">
                            <!--TODO - handle table-users style in a css file -->
                            <div style="height:100%;width:100%">
                                <img src="{% get_avatar_url user %}"> {{ user.get_nicename }}
                            </div>
                        </a>
                    </td>
                    <td>
                        {{ user.case_count }}
                    </td>
                    <td>
                        {{ user.case_assigned_sum }}
                    </td>
                    {# <td> #}
                    {#    {{ user.case_assigned_free }} #}
                    {# </td> #}
                    <td>
                        {{ user.case_assigned_moderated }}
                    </td>
                    <td>
                        {{ user.case_assigned_active }}
                    </td>
                    <td>
                        {{ user.case_assigned_closed }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="row text-center">
            {% bootstrap_paginate page_obj show_first_last="true" %}
        </div>
    </div>
</div>

{% endblock %}

poradnia/users/templates/users/user_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans 'User' %}: {{ user.username }} - {{ block.super }}{% endblock %}

{% block breadcrumbs_rows %}
    <li><a href="{{ user.get_absolute_url }}">{{ user }}</a></li>
    <li class="active">{% trans 'Account' %}</li>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-1">
            <h1>{% block header %}{% trans 'User' %}: {{ user.get_nicename }}{% endblock %}</h1>
            {% block form %}
            <form enctype="multipart/form-data" class="form-horizontal" method="post">
                {% csrf_token %}
                {% crispy form %}
            </form>
            {% endblock %}
        </div>
    </div>
{% endblock %}

poradnia/users/templates/users/user_info.html
{% extends "users/base.html" %}
{% load users_tags static i18n %}
{% block title %}{% trans 'User' %}: {{ object.get_nicename }} - {{ block.super }}{% endblock %}

{% block breadcrumbs_rows %}
    <li class="active">{{ object }}</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-1">
        <img src="{% get_avatar_url object %}">
        <h3><b>{% trans 'Username' %}:</b> {{ object.username }} &nbsp; &nbsp; &nbsp;
            <b>{% trans 'Full name' %}:</b> {{ object.nicename }}</h3>
        {% if object.is_staff %}
            <p>{% trans 'Is member of staff.' %}</p>
        {% endif %}
        {% if object.profile %}
            <p><span><b>{% trans 'Description' %}:</b></span><br>
                {{ object.profile.description|linebreaksbr }}</p>
        {% endif %}

    </div>
</div>

{% endblock content %}